name: Build Java Maven project

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Maven project
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
      - name: Build project
        run: |
          mvn install
      - name: Get artifacts
        run: |
          mkdir push
          cp ./advancedregionmarket/target/*.jar ./push
          rm -f ./push/original-*.jar
          rm -f ./push/*-shaded.jar
          rm -f ./push/*-sources.jar
          mv -f ./push/*-javadoc.jar ./push/JavaDocument.zip
      - name: Github release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: push/*